### ISSUE TITLE
Not working on 1803

### ISSUE THREAD

**Issue by andypillip** [JesperDramsch/kdbneo2#1]
Thank so much for a fix!

Unfortunately it doesn't seem to work on Windows 10 Enterprise 1803.
The layout is available in the list in regional settings, but will not appear in the tray.

Would you have an idea how to debug?

**Comment by andypillip** [comment]
Apparently a restart fixed it. Sorry for the disturbance.

**Comment by JesperDramsch** [comment]
Glad to hear! No worries, I'll close this then.
